name: Python checks (mypy + pytest)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-typecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        pipenv install --dev

    - name: Run mypy
      run: |
        pipenv run type-check

    - name: Run tests with coverage
      run: |
        git submodule update --init --recursive
        pipenv run coverage
